reserved = {
    'if': 'IF',
    'else': 'ELSE',
    'for': 'FOR',
    'while': 'WHILE',
    'in': 'IN',
    'func': 'FUNC',
    'is': 'IS',
    'obj': 'OBJ',
    'return': 'RETURN',
    'pass': 'PASS',
    'break': 'BREAK',
    'raise': 'RAISE',
    'continue': 'CONTINUE',
    'not': 'NOT',
    'assert': 'ASSERT',
    # Reserved types
    'int': 'INT_T',
    'float': 'FLOAT_T',
    'bool': 'BOOL_T',
    'string': 'STRING_T',
}

tokens = (
    'INT',
    'FLOAT',
    'EQ',
    'GEQ',
    'LEQ',
    'PLUS_ASSIGNMENT',
    'MINUS_ASSIGNMENT',
    'TIMES_ASSIGNMENT',
    'DIVIDE_ASSIGNMENT',
    'IDENTIFIER',
    'COMMENT',
) + tuple(reserved.values())

literals = [
    '+',
    '-',
    '*',
    '/',
    '(',
    ')',
    '{',
    '}',
    '[',
    ']',
    '.',
    ',',
    ':',
    '=',
    '<',
    '>',
]

